name: 'tauri'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  macos-arm:
    uses: ./.github/workflows/build-and-smoke-test.yaml
    with:
      platform: 'macos-latest' # for Arm based macs (M1 and above).
      arch: 'aarch64'
      args: '--target aarch64-apple-darwin'
      pkgConfigPath: '/opt/homebrew/lib/pkgconfig'
      artifact-name: 'tauri-bundles-macos-latest-aarch64'
    secrets: inherit

  macos-intel:
    uses: ./.github/workflows/build-and-smoke-test.yaml
    with:
      platform: 'macos-15-intel'
      arch: 'x86_64'
      args: '--target x86_64-apple-darwin'
      pkgConfigPath: '/usr/local/lib/pkgconfig'
      artifact-name: 'tauri-bundles-macos-15-intel-x86_64'
    secrets: inherit

  linux-amd64:
    uses: ./.github/workflows/build-and-smoke-test.yaml
    with:
      platform: 'ubuntu-22.04'
      arch: 'amd64'
      args: ''
      pkgConfigPath: '/usr/local/lib/pkgconfig'
      artifact-name: 'tauri-bundles-ubuntu-22.04'
    secrets: inherit

  linux-arm64:
    uses: ./.github/workflows/build-and-smoke-test.yaml
    with:
      platform: 'ubuntu-22.04-arm' # Only available in public repos.
      arch: 'arm64'
      args: ''
      pkgConfigPath: '/usr/local/lib/pkgconfig'
      artifact-name: 'tauri-bundles-ubuntu-22.04-arm'
    secrets: inherit

  windows-x64:
    uses: ./.github/workflows/build-and-smoke-test.yaml
    with:
      platform: 'windows-latest'
      arch: 'x64'
      args: ''
      pkgConfigPath: 'C:\\vcpkg\\installed\\x64-windows-static-md\\lib\\pkgconfig'
      artifact-name: 'tauri-bundles-windows-latest'
    secrets: inherit
